# Generated by Django 4.0.5 on 2022-06-11 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(verbose_name='Estado')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.curso', verbose_name='Curso')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(verbose_name='Estado')),
                ('nota', models.FloatField(verbose_name='Nota')),
                ('curTemStem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.curtemstem', verbose_name='CurTemStem')),
                ('inscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.inscripcion', verbose_name='Inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(verbose_name='Estado')),
                ('nota', models.FloatField(verbose_name='Nota')),
                ('actDetOpt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.actdetopt', verbose_name='ActDetOpt')),
                ('progreso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.progreso', verbose_name='Progreso')),
            ],
        ),
    ]
