# Generated by Django 4.0.5 on 2022-07-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0002_subsubtema_tema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre de la Actividad'),
        ),
    ]
