# Generated by Django 4.0.5 on 2022-06-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0002_inscripcion_progreso_progresodet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción del Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado'), ('En Proceso', 'En Proceso')], default='Cerrado', max_length=10, null=True, verbose_name='Estado del Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_final',
            field=models.DateTimeField(null=True, verbose_name='Fecha Final'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_inicial',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicial'),
        ),
    ]
