# Generated by Django 4.0.5 on 2022-06-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0003_alter_curso_descripcion_alter_curso_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Cerrado', max_length=10, null=True, verbose_name='Estado del Curso'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, null=True, verbose_name='Estado del Tema'),
        ),
    ]
