# Generated by Django 4.0.5 on 2022-06-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0004_alter_curso_estado_alter_tema_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtema',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, null=True, verbose_name='Estado del Subtema'),
        ),
    ]
