# Generated by Django 4.0.5 on 2022-08-01 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0004_abstracurso_alter_user_estado_alter_user_usuario_bot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usuario_bot',
            new_name='tipo_user',
        ),
    ]
