# Generated by Django 4.0.5 on 2022-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0005_alter_subtema_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtemstem',
            name='fecha_f',
            field=models.DateTimeField(unique=True, verbose_name='Fecha Fin'),
        ),
    ]
