# Generated by Django 4.0.5 on 2022-08-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0006_abstracurso_nombre_nivel_tema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_user',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Estudiante', 'Estudiante'), ('Docente', 'Docente'), ('Bot', 'Bot'), ('Si', 'Si'), ('No', 'No')], default='Estudiante', max_length=13, null=True, verbose_name='Usuario Bot'),
        ),
    ]
