# Generated by Django 4.0.5 on 2022-06-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0008_alter_user_usuario_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.curso', verbose_name='Curso'),
        ),
    ]
