# Generated by Django 4.0.5 on 2022-08-04 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0008_alter_user_tipo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act_Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(null=True, verbose_name='Orden')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Act_Pregunta_Opt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción ActDetOpt')),
                ('orden', models.IntegerField(null=True, verbose_name='Orden')),
                ('opt_correcta', models.IntegerField(null=True, verbose_name='Opción Correcta')),
                ('act_Pregunta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.act_pregunta', verbose_name='ActividadDet')),
            ],
        ),
        migrations.CreateModel(
            name='Ctsd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(null=True, unique=True, verbose_name='Orden')),
            ],
        ),
        migrations.CreateModel(
            name='Prog_Acti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(null=True, verbose_name='Estado')),
                ('nota', models.FloatField(null=True, verbose_name='Nota')),
                ('porcentaje', models.FloatField(null=True, verbose_name='Porcentaje avance')),
            ],
        ),
        migrations.CreateModel(
            name='Prog_Preg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(null=True, verbose_name='Nota')),
                ('porcentaje', models.FloatField(null=True, verbose_name='Porcentaje avance')),
                ('act_Pregunta_Opt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.act_pregunta_opt', verbose_name='ActDetOpt')),
            ],
        ),
        migrations.RemoveField(
            model_name='actividaddet',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='curTemStem',
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='inscripcion',
        ),
        migrations.RemoveField(
            model_name='progresodet',
            name='actDetOpt',
        ),
        migrations.RemoveField(
            model_name='progresodet',
            name='progreso',
        ),
        migrations.RemoveField(
            model_name='curtemstem',
            name='subSubtema',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='nota_def',
            field=models.FloatField(null=True, verbose_name='Nota Definitiva'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='porcentaje_prog',
            field=models.FloatField(null=True, verbose_name='%. de Progreso'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción de La Actividad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='estado',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Estado de la Actividad'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_f',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_i',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='fecha',
            field=models.DateTimeField(null=True, verbose_name='Fecha/Hora'),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='mensaje',
            field=models.TextField(null=True, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='curtemstem',
            name='fecha_f',
            field=models.DateTimeField(null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='curtemstem',
            name='fecha_i',
            field=models.DateTimeField(null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='curtemstem',
            name='orden',
            field=models.IntegerField(null=True, unique=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.IntegerField(null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='subsubtema',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción Tema'),
        ),
        migrations.AlterField(
            model_name='subtema',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción Subtema'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción del Tema'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='estado',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='fecha_creacion',
            field=models.DateTimeField(null=True, verbose_name='Fecha Creación'),
        ),
        migrations.DeleteModel(
            name='ActDetOpt',
        ),
        migrations.DeleteModel(
            name='ActividadDet',
        ),
        migrations.DeleteModel(
            name='Progreso',
        ),
        migrations.DeleteModel(
            name='ProgresoDet',
        ),
        migrations.AddField(
            model_name='prog_preg',
            name='curTemStem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.curtemstem', verbose_name='CurTemStem'),
        ),
        migrations.AddField(
            model_name='prog_preg',
            name='prog_Acti',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.prog_acti', verbose_name='Progreso Actividad'),
        ),
        migrations.AddField(
            model_name='prog_acti',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.actividad', verbose_name='Actividad'),
        ),
        migrations.AddField(
            model_name='prog_acti',
            name='inscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.inscripcion', verbose_name='Inscripcion'),
        ),
        migrations.AddField(
            model_name='ctsd',
            name='curTemStem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.curtemstem', verbose_name='Detallado del Curso'),
        ),
        migrations.AddField(
            model_name='ctsd',
            name='subSubtema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.subsubtema', verbose_name='SubSubtema'),
        ),
        migrations.AddField(
            model_name='act_pregunta',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.actividad', verbose_name='Actividad'),
        ),
    ]
