# Generated by Django 4.0.5 on 2022-07-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0009_conversacion_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='tipo_mensje',
            field=models.CharField(choices=[('Link', 'Link'), ('Video', 'Video'), ('Lista', 'Lista'), ('Texto', 'Texto')], default='Texto', max_length=10, null=True, verbose_name='Estado del Tema'),
        ),
    ]
