# Generated by Django 4.0.5 on 2022-08-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0009_act_pregunta_act_pregunta_opt_ctsd_prog_acti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='nota_def',
            field=models.FloatField(default=0, null=True, verbose_name='Nota Definitiva'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='porcentaje_prog',
            field=models.FloatField(default=0, null=True, verbose_name='%. de Progreso'),
        ),
    ]
