# Generated by Django 4.0.5 on 2022-08-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0010_alter_inscripcion_nota_def_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curtemstem',
            name='subtema',
        ),
        migrations.AddField(
            model_name='ctsd',
            name='subtema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.subtema', verbose_name='Subtema'),
        ),
        migrations.CreateModel(
            name='Log_Curso_Inscrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_i', models.DateTimeField(null=True, verbose_name='Fecha/Hora Inicio')),
                ('date_time_f', models.DateTimeField(null=True, verbose_name='Fecha/Hora Fin')),
                ('inscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.inscripcion', verbose_name='Inscripcion')),
                ('subSubtema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.subsubtema', verbose_name='SubSubtema')),
                ('subtema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.subtema', verbose_name='Subtema')),
                ('tema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.tema', verbose_name='Tema')),
            ],
        ),
    ]
