# Generated by Django 4.0.5 on 2022-07-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0010_conversacion_tipo_mensje'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubtema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre tema nivel tres')),
                ('descripcion', models.TextField(verbose_name='Descripción Tema')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10, null=True, verbose_name='Estado del tema')),
                ('subtema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.subtema', verbose_name='Subtema')),
            ],
        ),
    ]
