# Generated by Django 4.0.6 on 2022-07-04 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0010_conversacion_tipo_mensje'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='inscripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.inscripcion', verbose_name='Inscripcion'),
        ),
    ]
