# Generated by Django 4.0.5 on 2022-08-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0011_remove_curtemstem_subtema_ctsd_subtema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('Inscrito', 'Inscrito'), ('En progreso', 'En progreso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Inscrito', max_length=11, null=True, verbose_name='Estado'),
        ),
    ]
