# Generated by Django 4.0.5 on 2022-07-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0011_subsubtema'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtemstem',
            name='subSubtema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.subsubtema', verbose_name='SubSubtema'),
        ),
    ]
