# Generated by Django 4.0.5 on 2022-08-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0012_alter_inscripcion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_curso_inscrip',
            name='estado_subsubtema',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Completado', 'Completado')], default='En proceso', max_length=10, null=True, verbose_name='Estado Detalle Subtema'),
        ),
        migrations.AddField(
            model_name='log_curso_inscrip',
            name='estado_subtema',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Completado', 'Completado')], default='En proceso', max_length=10, null=True, verbose_name='Estado Subtema'),
        ),
        migrations.AddField(
            model_name='log_curso_inscrip',
            name='estado_tema',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Completado', 'Completado')], default='En proceso', max_length=10, null=True, verbose_name='Estado Tema'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('Inscrito', 'Inscrito'), ('En proceso', 'En proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Inscrito', max_length=11, null=True, verbose_name='Estado'),
        ),
    ]
