# Generated by Django 4.0.5 on 2022-08-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0013_log_curso_inscrip_estado_subsubtema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curtemstem',
            name='orden',
            field=models.IntegerField(null=True, verbose_name='Orden'),
        ),
    ]
