# Generated by Django 4.0.5 on 2022-08-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0014_alter_curtemstem_orden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log_Curso_Inscrip',
        ),
    ]
