# Generated by Django 4.0.5 on 2022-08-24 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0015_delete_log_curso_inscrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(null=True, unique=True, verbose_name='Orden')),
                ('curTemStem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.curtemstem', verbose_name='Detallado del Curso')),
                ('subtema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.subtema', verbose_name='Subtema')),
            ],
        ),
        migrations.RemoveField(
            model_name='ctsd',
            name='curTemStem',
        ),
        migrations.RemoveField(
            model_name='ctsd',
            name='subtema',
        ),
        migrations.CreateModel(
            name='Prog_Tem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_i', models.DateTimeField(db_index=True, null=True, verbose_name='Fecha Inicio')),
                ('fecha_f', models.DateTimeField(db_index=True, null=True, verbose_name='Fecha Fin')),
                ('orden', models.IntegerField(null=True, unique=True, verbose_name='Orden')),
                ('curTemStem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.curtemstem', verbose_name='Detallado del Curso')),
                ('inscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.inscripcion', verbose_name='Inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Prog_Stem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(null=True, unique=True, verbose_name='Orden')),
                ('cts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.cts', verbose_name='Curso Tema Subtema')),
                ('prog_Tem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.prog_tem', verbose_name='Progreso Tema')),
            ],
        ),
        migrations.CreateModel(
            name='Prog_Sstem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(null=True, unique=True, verbose_name='Orden')),
                ('ctsd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.ctsd', verbose_name='Curso,Tema,Subtema,Detalle')),
                ('prog_Stem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.prog_stem', verbose_name='Progreso Tema')),
            ],
        ),
        migrations.AddField(
            model_name='ctsd',
            name='cts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appbot.cts', verbose_name='Curso Tema Subtema'),
        ),
    ]
