# Generated by Django 4.0.5 on 2022-08-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0016_cts_remove_ctsd_curtemstem_remove_ctsd_subtema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prog_tem',
            name='orden',
            field=models.IntegerField(null=True, verbose_name='Orden'),
        ),
    ]
