# Generated by Django 4.0.5 on 2022-08-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0018_alter_cts_orden_alter_ctsd_orden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='title',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Titulo'),
        ),
    ]
