# Generated by Django 4.0.5 on 2022-08-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0019_conversacion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='prog_sstem',
            name='fecha_f',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='prog_sstem',
            name='fecha_i',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AddField(
            model_name='prog_stem',
            name='fecha_f',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='prog_stem',
            name='fecha_i',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
