# Generated by Django 4.0.5 on 2022-09-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0020_prog_sstem_fecha_f_prog_sstem_fecha_i_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act_pregunta',
            name='tipo',
            field=models.IntegerField(null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='act_pregunta_opt',
            name='descripcion',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
    ]
