# Generated by Django 4.0.5 on 2022-09-08 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0021_alter_act_pregunta_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 23, 20, 8, 967499), null=True, verbose_name='Fecha Creación'),
        ),
    ]
