# Generated by Django 4.0.5 on 2022-09-18 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0022_alter_user_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act_pregunta_opt',
            name='opt_correcta',
            field=models.CharField(choices=[('Falsa', 'Falsa'), ('Correcta', 'Correcta')], default='Falsa', max_length=8, null=True, verbose_name='Esta opción es'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 17, 5, 23, 335556), null=True, verbose_name='Fecha Creación'),
        ),
    ]
