# Generated by Django 4.0.5 on 2022-10-05 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0025_alter_user_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='recurso',
            field=models.CharField(blank=True, choices=[('Enlace', 'Enlace'), ('Archivo', 'Archivo'), ('Video', 'Video')], max_length=7, null=True, verbose_name='Recurso'),
        ),
        migrations.AddField(
            model_name='tema',
            name='recurso_archivo',
            field=models.FileField(blank=True, null=True, upload_to='Tema/', verbose_name='Cargar archivo'),
        ),
        migrations.AddField(
            model_name='tema',
            name='recurso_link_video',
            field=models.TextField(blank=True, null=True, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 20, 50, 28, 761594), null=True, verbose_name='Fecha Creación'),
        ),
    ]
