# Generated by Django 4.0.5 on 2022-10-05 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0026_tema_recurso_tema_recurso_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubtema',
            name='recurso',
            field=models.CharField(blank=True, choices=[('Enlace', 'Enlace'), ('Archivo', 'Archivo'), ('Video', 'Video')], max_length=7, null=True, verbose_name='Recurso'),
        ),
        migrations.AddField(
            model_name='subsubtema',
            name='recurso_archivo',
            field=models.FileField(blank=True, null=True, upload_to='SubSubtema/', verbose_name='Cargar archivo'),
        ),
        migrations.AddField(
            model_name='subsubtema',
            name='recurso_link_video',
            field=models.TextField(blank=True, null=True, verbose_name='Enlace'),
        ),
        migrations.AddField(
            model_name='subtema',
            name='recurso',
            field=models.CharField(blank=True, choices=[('Enlace', 'Enlace'), ('Archivo', 'Archivo'), ('Video', 'Video')], max_length=7, null=True, verbose_name='Recurso'),
        ),
        migrations.AddField(
            model_name='subtema',
            name='recurso_archivo',
            field=models.FileField(blank=True, null=True, upload_to='Subtema/', verbose_name='Cargar archivo'),
        ),
        migrations.AddField(
            model_name='subtema',
            name='recurso_link_video',
            field=models.TextField(blank=True, null=True, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 21, 3, 49, 57309), null=True, verbose_name='Fecha Creación'),
        ),
    ]
