# Generated by Django 4.0.5 on 2022-10-05 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0027_subsubtema_recurso_subsubtema_recurso_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 7, 34, 38, 794629), null=True, verbose_name='Fecha Creación'),
        ),
    ]
