# Generated by Django 4.0.5 on 2022-10-16 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0028_alter_user_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='recurso',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Recurso'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='recurso_dir',
            field=models.TextField(blank=True, null=True, verbose_name='Direccion Recurso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 16, 45, 32, 697238), null=True, verbose_name='Fecha Creación'),
        ),
    ]
