# Generated by Django 4.0.5 on 2023-02-05 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0030_alter_subsubtema_nombre_alter_subtema_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 5, 12, 42, 57, 721499), null=True, verbose_name='Fecha Creación'),
        ),
    ]
