# Generated by Django 4.0.5 on 2023-02-12 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0031_alter_user_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_naci',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], db_index=True, default='Masculino', max_length=9, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 8, 53, 55, 948489), null=True, verbose_name='Fecha Creación'),
        ),
    ]
