# Generated by Django 4.0.5 on 2023-02-12 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0032_user_fecha_naci_user_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='estrato',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=1, null=True, verbose_name='Estrato'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 10, 38, 32, 124972), null=True, verbose_name='Fecha Creación'),
        ),
    ]
