# Generated by Django 4.0.5 on 2023-02-12 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0033_user_estrato_alter_user_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 11, 15, 28, 618766), null=True, verbose_name='Fecha Creación'),
        ),
    ]
