# Generated by Django 4.0.5 on 2023-02-25 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0035_alter_user_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubtema',
            name='recurso_archivo',
            field=models.FileField(blank=True, null=True, upload_to='SubSubtema', verbose_name='Cargar archivo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 15, 26, 25, 60092), null=True, verbose_name='Fecha Creación'),
        ),
    ]
