# Generated by Django 4.0.5 on 2023-02-25 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0036_alter_subsubtema_recurso_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 15, 38, 22, 618230), null=True, verbose_name='Fecha Creación'),
        ),
    ]
