# Generated by Django 4.0.5 on 2023-02-25 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbot', '0037_alter_user_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 15, 57, 39, 628315), null=True, verbose_name='Fecha Creación'),
        ),
    ]
